### ISSUE TITLE
Maybe add a custom README?

### ISSUE THREAD

**Issue by Reevak05** [CamShaft54/CarbonTechMod#2]
The README is a .txt, instead of a .md (Markdown). I'm not sure if this was deliberate, but Markdown has more formatting options and is generally better and more readable for READMEs. Perhaps after pulling #1 it can be changed to a .md, assuming it's possible and an improvement.

**Comment by MetalTurtle18** [comment]
Nononono. That is because he hasn't made a README. This is just the default forge download README. All that should be done here is create a new file called README.md .

**Comment by Reevak05** [comment]
Oh, okay.  I didn’t know that was the forge default.

**Comment by Reevak05** [comment]
I’ll update this issue then

**Comment by Reevak05** [comment]
@CamShaft54 enhancement

**Comment by Camshaft54** [comment]
Yeah I know @Reevak05, I need to add a README.MD. The README.txt is a default forge file, I will get rid of it soon.

**Comment by Camshaft54** [comment]
Fixed.
